version: "3.7"

services:
  angular:
    image: ttv2412/management_web_fe
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - API_URL=${API_URL}
      - SONAR_URL=${SONAR_URL}
    ports:
      - ${PORT}:${PORT}
