version: "3.7"

services:
  angular:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - API_URL=${API_URL}
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    ports:
      - ${PORT}:${PORT}
